### ISSUE TITLE
Wrong student ID

### ISSUE THREAD

**Issue by simonrenger** [BertHeesakkers/IGADPiGameServer#1]
You can still break the server with a wrong student ID.

`RakNet::RakString a_LoginID = "17009636";`

**Comment by Zandor300** [comment]
I guess the problem lies here:
https://github.com/BertHeesakkers/IGADPiGameServer/blob/1597cab67ac793a2d026abc804ebcf8e8bd5931b/Source/Server/Server.cpp#L354

**Comment by BertHeesakkers** [comment]
The server should return the EServerError_UserDataUnavailable message as it does in the other 2 cases where the user data was not found. I have removed the assert and replaced it with said message.
