### ISSUE TITLE
[Suggestion] EMessage_SendLobbyData 

### ISSUE THREAD

**Issue by simonrenger** [BertHeesakkers/IGADPiGameServer#13]
How would it be to have the possibility to query the current lobby in the following way:

`EMessage_SendLobbyData `
DATA1: CLIENT_ID
DATA2: GAME_ID

`EMessage_RecvLobbyData `
DATA1: GAME_ID
DATA2: number of user in lobby

DATA3-[n*] UserDataLobby

```cpp
struct UserDataLobby{
char* name;
uint32_t ClientID
}
````

How to use it:

```cpp
std::vector<UserDataLobby> udl;
for(int x = 0; x < DATA2;x++){
UserDataLobby userData;
bitstream.Read(userData);
udl.push_back(userData);
}
```

**Comment by Zandor300** [comment]
On it! ;)

**Comment by Zandor300** [comment]
I think `LobbyUserData` would be better.

**Comment by Zandor300** [comment]
Uuhh, `GameID` is the id of the game but will be created AFTER the game has started. I think this message applies only when in the lobby...

The `GameID` will be passed to the client using `EMessage_RecvGameJoined`.

**Comment by Zandor300** [comment]
Using following scheme now...

`EMessage_SendLobbyData`
DATA1: CLIENT_ID
DATA2: EGame

`EMessage_RecvLobbyData`
DATA2: EGame
DATA2: number of user in lobby

DATA3-[n*] UserDataLobby
