### ISSUE TITLE
CMake Error:  RakNet static debug library not found!

### ISSUE THREAD

**Issue by simonrenger** [BertHeesakkers/IGADPiGameServer#15]
```bash
-- Locating third party libraries
CMake Error at Applications/CMakeLists.txt:18 (message):
  RakNet static debug library not found!


-- Configuring incomplete, errors occurred!
```

**Comment by simonrenger** [comment]
# IGADPiGameServer
Game server created for educational purposes for IGAD (Breda University of Applied Sciences, the Netherlands)

<img src="https://insight.nhtv.nl/wp-content/uploads/2018/01/English-banner.jpg" />


## How to use

In order to learn how to use the server check out the [Documentation](/Documentation) there you will find help files for how to communicate with the server.

## Build

```
$ cd /server_root
$ cmake .
$ make install
```

### Dependencies

- CMake 3.9.9
- RakNet build as static lib

**Comment by simonrenger** [comment]
I did not submit a pull request on the readme file because of my spelling.

**Comment by Zandor300** [comment]
It's fine... Only thing is commas;

In order to learn how to use the server, check out the documentation, there you will find help files for how to communicate with the server.

**Comment by BertHeesakkers** [comment]
I will look into how to link directly to the RakNet repository on Github so it donwloads autmatically. The dependency on CMake is not 3.9.9 but 3.9.2 (latest version supported by Visual Studio 2017).

**Comment by Zandor300** [comment]
@BertHeesakkers See https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by Zandor300** [comment]
But I think that isn’t a good way to fix the problem 🤔

**Comment by simonrenger** [comment]
the problem I am having with cloning the raknet repo and build it myself does not work properly because it will not perfrom make install properly. its installing raknet inside of the repo folder instead of /usr/local/lib /usr/local/include

**Comment by simonrenger** [comment]
If I do:
```
$ git clone https://github.com/facebookarchive/RakNet.git
$ cd RakNet
$ cmake .
$ make install
$ cp Lib/RakNetLibStatic/libRakNetLibStatic.a /usr/local/lib64/libRakNetLibStatic.a
$ cp -R include/raknet /usr/local/include/raknet
```
 The I can run cmake with no problem

**Comment by Zandor300** [comment]
My script I shared some time ago will compile and move RakNet to the correct location:

http://git.zsinfo.nl/snippets/7

```bash
wget -O - http://git.zsinfo.nl/snippets/7/raw | bash
```

**Comment by simonrenger** [comment]
Yeah its not applicable because I am not building on a pi ^^ and hardcoded paths are a no go :P but yeah. I found some more bugs in the cmake file i gonna update it
