### ISSUE TITLE
set the right C++ Version

### ISSUE THREAD

**Issue by simonrenger** [BertHeesakkers/IGADPiGameServer#16]
I ran into trouble to compile the server. CMake is not setting the right C++ Version of the compiler. Its goes by default with C++98 (This can be my distribution) but to avoid this would be the solution add this to the main CMake file
```cpp
if(UNIX)
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=gnu++11")
endif()
```
I don't want to add this to the cmake file because I don't know if this is a general issue. I will try to build the server on a different machine (my pi) as well if that is there the case as well then I will add propose a patch.

**Comment by Zandor300** [comment]
Can be closed, since https://github.com/BertHeesakkers/IGADPiGameServer/pull/19 implements this?
